consul:
  # consul host
  host: "www.consul.com"
  # consul port
  port: 8500
  # consul scheme
  scheme: "http"
  # consul ACL token
  token: ""
search:
  # default search root
  root: ""
  # search results limit
  limit: 10
  # result output type, text, json or csv
  output_type: "text"
  # result output file, supported for json output type
  output_file: ""
  # cache file
  cache: ".cache"
  # cache expire seconds
  cache_ttl: 300
log:
  # log level
  log_level: "INFO"
